# Generated by Django 5.0 on 2023-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to='')),
                ('post_description', models.TextField()),
                ('post_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
